# Generated by Django 5.1.4 on 2024-12-07 21:07

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[users.validators.validate_phone_number]),
        ),
    ]
