# Generated by Django 5.1.4 on 2024-12-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_verify_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
